In [1]:
import pandas as pd

from api.openrouteservice_api import Coordinate, get_distance_between_two_coordinates

In [13]:
df_hdb = pd.read_csv('./data/modified/hdb_cleaned_data.csv')
df_hdb

,Unnamed: 0,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price,address
0,0,2015-01,ANG MO KIO,3 ROOM,174,ANG MO KIO AVE 4,07 TO 09,60.0,Improved,1986,70,255000.0,174 ANG MO KIO AVE 4
1,1,2015-01,ANG MO KIO,3 ROOM,541,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1981,65,275000.0,541 ANG MO KIO AVE 10
2,2,2015-01,ANG MO KIO,3 ROOM,163,ANG MO KIO AVE 4,01 TO 03,69.0,New Generation,1980,64,285000.0,163 ANG MO KIO AVE 4
3,3,2015-01,ANG MO KIO,3 ROOM,446,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1979,63,290000.0,446 ANG MO KIO AVE 10
4,4,2015-01,ANG MO KIO,3 ROOM,557,ANG MO KIO AVE 10,07 TO 09,68.0,New Generation,1980,64,290000.0,557 ANG MO KIO AVE 10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37148,37148,2016-12,YISHUN,5 ROOM,297,YISHUN ST 20,13 TO 15,112.0,Improved,2000,82,488000.0,297 YISHUN ST 20
37149,37149,2016-12,YISHUN,5 ROOM,838,YISHUN ST 81,01 TO 03,122.0,Improved,1987,69,455000.0,838 YISHUN ST 81
37150,37150,2016-12,YISHUN,EXECUTIVE,664,YISHUN AVE 4,10 TO 12,181.0,Apartment,1992,74,778000.0,664 YISHUN AVE 4
37151,37151,2016-12,YISHUN,EXECUTIVE,325,YISHUN CTRL,01 TO 03,146.0,Maisonette,1988,70,575000.0,325 YISHUN CTRL
37152,37152,2016-12,YISHUN,MULTI-GENERATION,666,YISHUN AVE 4,10 TO 12,164.0,Multi Generation,1987,70,735000.0,666 YISHUN AVE 4

In [11]:
import requests

def get_geocoordinates_from_address(address):
    url = f"https://www.onemap.gov.sg/api/common/elastic/search?searchVal={address}&returnGeom=Y&getAddrDetails=Y&pageNum=1"
    
    response = requests.get(url)    
    data = response.json()

    # Check if there are results
    if data['results']:
        first_result = data['results'][0]
        latitude = first_result['LATITUDE']
        longitude = first_result['LONGITUDE']
        return (latitude, longitude)
    else:
        return (None, None)

In [12]:
get_geocoordinates_from_address("Ang Mo Kio MRT Station")

Address: Ang Mo Kio MRT Station
Coordinates: Latitude 1.36942855699191, Longitude 103.849455226442

### Calculate distances for POI
Purpose: To calculate distances from addresses to POI
- distance2cbd
- distance2nearestschool
- distance2nearestmrt

How: Use OpenRouteService API to get distances

In [ ]:
CENTRAL_BUSINESS_DISTRICT = Coordinate(lon=103.851784, lat=1.287953)

# get distance to CBD for every address in data
df_hdb['distance2cbd'] = df_hdb['']